name: Nuget - Release

on:
  push:
    branches: [ main ]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Instalando as dependências
      run: |
        cd Firenet/
        dotnet restore
    
    - name: Buildando os pacotes
      run: |
        cd Firenet/
        dotnet build --configuration Release --no-restore
    
    - name: Publicando no Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Firenet/Firenet/Firenet.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
